"""empty message

Revision ID: ab4122c2e433
Revises: 1e281951e69a
Create Date: 2023-07-09 15:44:28.404492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4122c2e433'
down_revision = '1e281951e69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('short_url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('short_url', schema=None) as batch_op:
        batch_op.drop_column('custom_url')

    # ### end Alembic commands ###
